### ISSUE TITLE
Support for Google Cast devices.

### ISSUE THREAD

**Issue by mcv93us** [energywave/homeassistant-packages#1]
I had been using the first version of this package for some time and I was pleased to see that there has been an evolution.
Wondering if you will ever implement support for Google products like the Nest mini ?? I am currently using two of them and I have appropriately modified the multinotify code to adapt it to my needs, with the limits of the case (the resumption of music after a message does not work and the entity `"media_player.ovunque"` does not work), for the rest works fine.
I am available for any tests!

**Comment by energywave** [comment]
I'm planning to add some things like Pushover, HTML5 and maybe Telegram. As I don't have Google Home devices at the moment I cannot add it. It would be a nice add, however. I'll maybe buy a Google device to develop it or rely on someone (you? :) ) that implemented it by adapting the code to fit it in the multinotify. I can ask some other google users to test it but I don't like so much the hypothesis to not test it by my self before a release of the update...

That said, as notifications options will be a lot, I'm also planning to create another script, that rely on the multinotify under the hood, where you specify only the "kind" of notification and there, in a centralized way, there is the information of what services to use to send that kind of notification.
EDIT: ok, I've just bought a Google Nest Mini... :) I'll work on it. In the meanwhile if you have suggestions or some piece of code to help me.... you're welcome.

**Comment by mcv93us** [comment]
I have attached the package with the changes I made to make it work with the Google Nest mini; I put the extension .txt as with .yaml it did not make me attach it.
[multinotify.txt](https://github.com/energywave/homeassistant-packages/files/7900599/multinotify.txt)

**Comment by energywave** [comment]
Hello, sorry for delay but I've implemented (well some time ago) Google Home devices. It's far to be optimal yet (it doesn't restore volume yet, music is by far too much of effort, I'll never implement music restore).
there are so MANY new implementations that I'm migrating multinotify on it's own repo here: https://github.com/energywave/multinotify
I have many improvements on my todo list...
Thanks for your interest!
