### ISSUE TITLE
New implementation request

### ISSUE THREAD

**Issue by mcv93us** [energywave/homeassistant-packages#2]
Good morning,
I saw that you are working on version 3 of the package and for that I wanted to ask you if it is possible to make another implementation: I would like there to be the possibility, as an alternative to a spoken message, to play a WAV / MP3 file as an announcement; I currently use some MP3 with modified voice (darker and more disturbing) in my system when my parents come home while I'm away, but it could be used to play any sound.
Tell me what you think!

**Comment by energywave** [comment]
Hello, sorry I'm replying with "some delay" :D If you mean on Alexa devices there is already such a possibility but it's a little cumbersome as Amazon has many constraints for it... I just wrote an article about SSML (that you can use for that purpose with the tag <audio> described here: https://henriksozzi.it/2022/08/notifiche-alexa-in-home-assistant-piu-personali/#Audio
The article is in italian language but I think tou can translate it and it will be understandable.
PS: I'm migrating the multinotify on it's own repo here: https://github.com/energywave/multinotify

**Comment by mcv93us** [comment]
I was referring to the Google Home devices, however in the meantime I too have been busy and implemented a rudimentary MP3 support by copying and modifying part of the multinotify code.
I have seen and also tested the latest news you have implemented, a really great job !!!
I'm afraid you will soon have to put your hand to the code to adapt it to a future breaking-change modification of the companion APP: https://github.com/home-assistant/android/pull/1759 , judging by the length of the log I think the new version will not be long in coming out.
